# Generated by Django 4.2 on 2023-04-28 00:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='LIKES',
            field=models.ManyToManyField(blank=True, related_name='No_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='FOLLOWERS',
            field=models.ManyToManyField(blank=True, related_name='No_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='FOLLOWING',
            field=models.ManyToManyField(blank=True, related_name='No_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
